server:
  port: 9007
spring:
  application:
    name: tenquare-search
  data:
    elasticsearch:
      cluster-nodes: 192.168.11.129:9300
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka