server:
  port: 9009
spring:
  application:
    name: tensquare-sms #指定服务名
  redis:
    host: 192.168.11.129
  rabbitmq:
    host: 192.168.11.129
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka