server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.155.128:3306/tensquare_qa?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
jwt:
  config:
    key: itcast       #密钥
    num: 86400000  #设置token过期时间为一天
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
feign:
  hystrix:
    enabled: true