server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.11.130
      database: spitdb
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka