server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.155.128:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.155.128
  rabbitmq:
    host: 192.168.155.128
jwt:
  config:
    key: itcast       #密钥
    num: 86400000  #设置token过期时间为一天
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka